import type { Metadata } from "next";
import { Space_Grotesk, Inter} from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Landing Page",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"], 
  variable: "--font-inter", 
  weight: ["400", "500", "700"], 
});
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"], 
  variable: "--font-space-grotesk", 
  weight: ["400", "500", "700"], 
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${spaceGrotesk.variable}  sans-serif antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
